### ISSUE TITLE
Error when building OS2

### ISSUE THREAD

**Issue by TeLLie** [fairybow/fernanda#3]
Hi
I use gcc 12.2.0 and QT 6
When building i get this errors...

G:/fernanda/fernanda/src/archiver.cpp: In member function 'void Archiver::create(FsPath, QVector<Io::ArcWRPaths>)':
G:/fernanda/fernanda/src/archiver.cpp:19:36: error: no matching function for call to 'QFile::copy(std::filesystem::__cxx11::path&, std::filesystem::__cxx11::path&)'
   19 |                         QFile::copy(entry.readFullPath.value(), temp_w_path);
      |                         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from h:/usr/local1220/include/QtCore/qdir.h:44,
                 from h:/usr/local1220/include/QtCore/QDir:1,
                 from G:/fernanda/fernanda/src/path.h:11,
                 from G:/fernanda/fernanda/src/io.h:5,
                 from G:/fernanda/fernanda/src/archiver.h:8,
                 from G:/fernanda/fernanda/src/archiver.cpp:3:
h:\usr\local1220/include/QtCore/qfile.h:214:10: note: candidate: 'template<class T, typename std::enable_if<is_same_v<std::filesystem::__cxx11::path, T>, int>::type <anonymous> > bool QFile::copy(const T&)'
  214 |     bool copy(const T &newName)
      |          ^~~~
h:\usr\local1220/include/QtCore/qfile.h:214:10: note:   template argument deduction/substitution failed:
G:/fernanda/fernanda/src/archiver.cpp:19:36: note:   candidate expects 1 argument, 2 provided
   19 |                         QFile::copy(entry.readFullPath.value(), temp_w_path);
      |                         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
h:\usr\local1220/include/QtCore/qfile.h:209:10: note: candidate: 'bool QFile::copy(const QString&)'
  209 |     bool copy(const QString &newName);
      |          ^~~~
h:\usr\local1220/include/QtCore/qfile.h:209:10: note:   candidate expects 1 argument, 2 provided
h:\usr\local1220/include/QtCore/qfile.h:219:17: note: candidate: 'static bool QFile::copy(const QString&, const QString&)'
  219 |     static bool copy(const QString &fileName, const QString &newName);
      |                 ^~~~
h:\usr\local1220/include/QtCore/qfile.h:219:37: note:   no known conversion for argument 1 from 'std::filesystem::__cxx11::path' to 'const QString&'
  219 |     static bool copy(const QString &fileName, const QString &newName);
      |                      ~~~~~~~~~~~~~~~^~~~~~~~
make[2]: *** [CMakeFiles/fernanda.dir/fernanda/src/archiver.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from G:/fernanda/fernanda/src/story.h:7,
                 from G:/fernanda/fernanda/src/fernanda.h:12,
                 from G:/fernanda/cmake-1220/fernanda_autogen/MJIP5XB4Z4/moc_fernanda.cpp:10,
                 from G:/fernanda/cmake-1220/fernanda_autogen/mocs_compilation.cpp:5:
G:/fernanda/fernanda/src/sample.h: In function 'void Sample::makeRc(std::filesystem::__cxx11::path)':
G:/fernanda/fernanda/src/sample.h:51:36: error: no matching function for call to 'QFile::copy(std::filesystem::__cxx11::path&, std::filesystem::__cxx11::path&)'
   51 |                         QFile::copy(source, target);
      |                         ~~~~~~~~~~~^~~~~~~~~~~~~~~~
In file included from h:/usr/local1220/include/QtCore/qdir.h:44,
                 from h:/usr/local1220/include/QtCore/QDir:1,
                 from G:/fernanda/fernanda/src/path.h:11,
                 from G:/fernanda/fernanda/src/io.h:5,
                 from G:/fernanda/fernanda/src/colorbar.h:5,
                 from G:/fernanda/cmake-1220/fernanda_autogen/MJIP5XB4Z4/moc_colorbar.cpp:10,
                 from G:/fernanda/cmake-1220/fernanda_autogen/mocs_compilation.cpp:2:
h:\usr\local1220/include/QtCore/qfile.h:214:10: note: candidate: 'template<class T, typename std::enable_if<is_same_v<std::filesystem::__cxx11::path, T>, int>::type <anonymous> > bool QFile::copy(const T&)'
  214 |     bool copy(const T &newName)
      |          ^~~~
h:\usr\local1220/include/QtCore/qfile.h:214:10: note:   template argument deduction/substitution failed:
G:/fernanda/fernanda/src/sample.h:51:36: note:   candidate expects 1 argument, 2 provided
   51 |                         QFile::copy(source, target);
      |                         ~~~~~~~~~~~^~~~~~~~~~~~~~~~
h:\usr\local1220/include/QtCore/qfile.h:209:10: note: candidate: 'bool QFile::copy(const QString&)'
  209 |     bool copy(const QString &newName);
      |          ^~~~
h:\usr\local1220/include/QtCore/qfile.h:209:10: note:   candidate expects 1 argument, 2 provided
h:\usr\local1220/include/QtCore/qfile.h:219:17: note: candidate: 'static bool QFile::copy(const QString&, const QString&)'
  219 |     static bool copy(const QString &fileName, const QString &newName);
      |                 ^~~~
h:\usr\local1220/include/QtCore/qfile.h:219:37: note:   no known conversion for argument 1 from 'std::filesystem::__cxx11::path' to 'const QString&'
  219 |     static bool copy(const QString &fileName, const QString &newName);
      |                      ~~~~~~~~~~~~~~~^~~~~~~~
make[2]: *** [CMakeFiles/fernanda.dir/fernanda_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/fernanda.dir/all] Error 2
make: *** [all] Error 2

Any idea??

**Comment by fairybow** [comment]
Hey! Thanks for letting me know about this. I have some ideas for what may be going on, so I will try to implement a fix right now.

**Comment by fairybow** [comment]
[This](https://github.com/fairybow/fernanda/releases/tag/v0.8.3-beta18) should hopefully address the issue. Let me know if it works for you whenever you have the chance. Thanks again!

**Comment by TeLLie** [comment]
Hii

This indeed fix those erors, thankz for the fast fix :)
